pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'build.bat'
                mail bcc: '', body: "构建版本成功", cc: '', charset: 'UTF-8', from: '13580805286@163.com', mimeType: 'text/plain', replyTo: '', subject: "构建版本成功", to: "815447838@qq.com";
            }
        }

        stage('Dev_Test'){
            steps {
                bat 'echo 等待开发人员测试通过，通过后再继续'
            }
        }

        stage('QA_Test') {
            steps {
                echo '执行自动化部署...'
                bat 'echo 执行自动化测试...'
               

               {
                    bat 'echo 自动化测试'
                }

            }
        }
    }
}
